apiVersion: apps/v1
kind: Deployment
metadata:
  name: treasure-miguel
  namespace: treasure-hunt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: treasure-miguel
  template:
    metadata:
      labels:
        app: treasure-miguel
    spec:
      containers:
        - name: web
          image: ghcr.io/mamp29/treasure-new:latest
          ports:
            - containerPort: 80
          env:
            - name: TITLE
              value: "Treasure Hunt — Miguel"
            - name: STUDENT
              value: "Miguel Muñoz 2274590"
            - name: SALT
              value: "DS3univalle"
            - name: KEY_HASH
              value: "58e90841e22f93fab9ffadeaad01dec797f71ff12e2195c45f8b0966be362698"
            - name: CLUE
              valueFrom:
                secretKeyRef:
                  name: miguel-clue
                  key: CLUE
---
apiVersion: v1
kind: Service
metadata:
  name: treasure-miguel
  namespace: treasure-hunt
spec:
  selector:
    app: treasure-miguel
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 32380   # (opcional) fija uno en el rango 30000–32767
  type: NodePort

