apiVersion: apps/v1
kind: Deployment
metadata:
  name: treasure-sebas
  namespace: treasure-hunt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: treasure-sebas
  template:
    metadata:
      labels:
        app: treasure-sebas
    spec:
      containers:
        - name: web
          image: oviedosebastian/treasure-new
          ports:
            - containerPort: 80
          env:
            - name: TITLE
              value: "Treasura Hunt Sebas"
            - name: STUDENT
              value: "Sebastian Oviedo 2510104"
            - name: SALT
              value: "DS3univalle"
            - name: KEY_HASH
              value: "3a35b203938ceca3d0a98a6524b4b209deb5bce386b138a1e26d6e39cc066e2c"
            - name: CLUE
              valueFrom:
                secretKeyRef:
                  name: sebas-clue
                  key: CLUE
---
apiVersion: v1
kind: Service
metadata:
  name: treasure-sebas
  namespace: treasure-hunt
spec:
  selector:
    app: treasure-sebas
  ports:
    - name: http
      port: 80
      targetPort: 80
      # nodePort: 31080   # (opcional) fija uno en el rango 30000–32767
  type: NodePort

